import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./Components/Navbar";
import { Provider } from "./Components/Provider";
import Footer from "./Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Muzio",
  description: "Generated by create next app",
  icons : {
    icon : '/logo.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
    <html lang="en">
          
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >  <Navbar/> 
 <main >
        {children}
     
        </main>
        <Footer/>
      </body>
 
    </html>
    </Provider>
  );
}
